# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "efad862fb03d8d529428b4ba1907c4c7"
application_url = "https://states-gospel-mass-por.trycloudflare.com"
embedded = true
name = "dealer-details-app"
handle = "dealer-details-app"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://states-gospel-mass-por.trycloudflare.com/auth/callback",
  "https://states-gospel-mass-por.trycloudflare.com/auth/shopify/callback",
  "https://states-gospel-mass-por.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://states-gospel-mass-por.trycloudflare.com"
subpath = "om-dealer-details"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
