# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b5845b5325aac64107c05dc38e5d56f"
name = "dealer-details-app"
handle = "dealer-details-app-1"
application_url = "https://setup-planners-violin-geneva.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://setup-planners-violin-geneva.trycloudflare.com/auth/callback",
  "https://setup-planners-violin-geneva.trycloudflare.com/auth/shopify/callback",
  "https://setup-planners-violin-geneva.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://setup-planners-violin-geneva.trycloudflare.com"
subpath = "om-dealer-details"
prefix = "apps"

[pos]
embedded = false
